[package]
name = "acnh-backup"
version = "0.1.0"
edition = "2021"

# Add your authors here
authors = ["KuramaSyu"]

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
crossterm = "0.28.1"
dialoguer = "0.11.0"
walkdir = "2.5.0"
whoami = "1.5.1"
zip = "2.2.0"
zip-extensions = "0.8.1"
